"""initial migration

Revision ID: 2a28ac0c53ac
Revises: 
Create Date: 2026-05-16 01:32:21.073737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a28ac0c53ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_boost', schema=None) as batch_op:
        batch_op.alter_column('applied_vote_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_boost', schema=None) as batch_op:
        batch_op.alter_column('applied_vote_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    # ### end Alembic commands ###
